<script setup lang="ts">
import { ref } from 'vue';
import {
  X,
  Copy,
  Check,
  Download,
  FileText,
  Printer,
  ExternalLink,
} from 'lucide-vue-next';
import type { ComplianceTask } from '@/stores/taskStore';

const props = defineProps<{
  isOpen: boolean;
  task: ComplianceTask | null;
}>();

const emit = defineEmits<{
  (e: 'close'): void;
}>();

const isCopied = ref(false);

const generateMarkdownReport = (): string => {
  if (!props.task) return '';
  const t = props.task;
  let md = `# Regulatory Compliance Intelligence Report\n\n`;
  md += `**Task Title:** ${t.title}\n`;
  md += `**Topic / Scope:** ${t.topic || 'General Regulatory Compliance'}\n`;
  md += `**Jurisdiction:** ${t.jurisdiction}\n`;
  md += `**Status:** ${t.status}\n`;
  md += `**Generated Date:** ${t.updatedAt || t.createdAt}\n`;
  md += `**Lead Reviewer:** ${t.owner}\n\n`;
  md += `---\n\n`;

  if (t.questions && t.questions.length > 0) {
    md += `## Compliance Inquiries & Authoritative Findings\n\n`;
    t.questions.forEach((q, idx) => {
      md += `### ${idx + 1}. ${q.questionText}\n\n`;
      if (q.summary) {
        md += `> **Executive Summary:** ${q.summary}\n\n`;
      }

      md += `#### Authoritative Official Sources Retrieved:\n`;
      q.retrievedUrls.forEach((url) => {
        md += `- [${url.title}](${url.url}) — *${url.authority} (${url.jurisdiction})* [${url.relevanceTag || 'Official Source'}]\n`;
      });
      md += `\n`;

      md += `#### Regulatory Analysis & Findings:\n${q.llmAnswer}\n\n`;

      if (q.citations && q.citations.length > 0) {
        md += `#### Verified Statutory Excerpts & Citations:\n`;
        q.citations.forEach((c) => {
          md += `- **[${c.pin}]** ${c.sourceTitle} (${c.clause || ''})\n  > "${c.excerpt}"\n`;
        });
        md += `\n`;
      }
      md += `---\n\n`;
    });
  }

  md += `\n*Confidential — Generated by Regulatory Monitoring & Compliance Workspace.*`;
  return md;
};

const handleCopyMarkdown = async () => {
  const md = generateMarkdownReport();
  try {
    await navigator.clipboard.writeText(md);
    isCopied.value = true;
    setTimeout(() => {
      isCopied.value = false;
    }, 2000);
  } catch (err) {
    console.warn('Failed to copy report to clipboard', err);
  }
};

const handleDownloadMarkdown = () => {
  const md = generateMarkdownReport();
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${props.task?.title.toLowerCase().replace(/[^a-z0-9]/g, '_') || 'compliance_report'}.md`;
  a.click();
  URL.revokeObjectURL(url);
};

const handlePrint = () => {
  window.print();
};
</script>

<template>
  <Teleport to="body">
    <div
      v-if="isOpen && task"
      class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-neutral-900/50 backdrop-blur-xs select-text overflow-y-auto animate-in fade-in duration-150"
    >
      <div
        class="bg-white rounded-2xl shadow-2xl border border-neutral-200 w-full max-w-3xl overflow-hidden flex flex-col my-8 max-h-[90vh]"
        @click.stop
      >
        <!-- Modal Header -->
        <div class="px-6 py-4 border-b border-neutral-100 flex items-center justify-between bg-neutral-50/70">
          <div class="flex items-center gap-2.5">
            <div class="w-8 h-8 rounded-xl bg-blue-600 flex items-center justify-center text-white shadow-2xs">
              <FileText class="w-4 h-4" />
            </div>
            <div>
              <h3 class="text-sm sm:text-base font-bold text-neutral-900">
                Compliance Intelligence Report
              </h3>
              <p class="text-xs text-neutral-500">
                Auditable dossier with authoritative source URLs & text citations
              </p>
            </div>
          </div>

          <div class="flex items-center gap-2">
            <button
              @click="handleCopyMarkdown"
              class="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-neutral-200 hover:bg-neutral-100 text-xs font-semibold text-neutral-700 transition-colors cursor-pointer"
              title="Copy Markdown"
            >
              <Check v-if="isCopied" class="w-3.5 h-3.5 text-emerald-600" />
              <Copy v-else class="w-3.5 h-3.5 text-neutral-500" />
              <span>{{ isCopied ? 'Copied' : 'Copy MD' }}</span>
            </button>
            <button
              @click="handleDownloadMarkdown"
              class="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-neutral-200 hover:bg-neutral-100 text-xs font-semibold text-neutral-700 transition-colors cursor-pointer"
              title="Download File"
            >
              <Download class="w-3.5 h-3.5 text-neutral-500" />
              <span>Download</span>
            </button>
            <button
              @click="handlePrint"
              class="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-neutral-200 hover:bg-neutral-100 text-xs font-semibold text-neutral-700 transition-colors cursor-pointer"
              title="Print"
            >
              <Printer class="w-3.5 h-3.5 text-neutral-500" />
            </button>
            <button
              @click="emit('close')"
              class="text-neutral-400 hover:text-neutral-700 p-1 rounded-lg hover:bg-neutral-100 transition-colors cursor-pointer ml-1"
            >
              <X class="w-5 h-5" />
            </button>
          </div>
        </div>

        <!-- Report Content Preview -->
        <div class="p-6 sm:p-8 space-y-6 overflow-y-auto flex-1 font-sans text-xs sm:text-sm text-neutral-800 print:p-0">
          <!-- Report Header Banner -->
          <div class="border-b border-neutral-200 pb-5">
            <div class="flex items-center justify-between gap-4 flex-wrap mb-2">
              <span class="text-xs font-bold uppercase tracking-wider text-blue-600 bg-blue-50 px-2.5 py-0.5 rounded-md">
                Formal Compliance Report
              </span>
              <span class="text-xs text-neutral-500 font-mono">
                Date: {{ task.updatedAt || task.createdAt }}
              </span>
            </div>
            <h1 class="text-lg sm:text-xl font-bold text-neutral-900 tracking-tight">
              {{ task.title }}
            </h1>
            <div class="flex items-center gap-3 mt-2 text-xs text-neutral-600 flex-wrap">
              <span><strong>Topic:</strong> {{ task.topic || 'General Compliance' }}</span>
              <span>•</span>
              <span><strong>Jurisdiction:</strong> {{ task.jurisdiction }}</span>
              <span>•</span>
              <span><strong>Reviewer:</strong> {{ task.owner }}</span>
            </div>
          </div>

          <!-- Questions & Findings Section -->
          <div class="space-y-6">
            <div
              v-for="(q, idx) in task.questions"
              :key="q.id"
              class="border border-neutral-200 rounded-xl p-5 bg-neutral-50/40 space-y-4"
            >
              <!-- Question Header -->
              <div>
                <span class="text-[11px] font-bold text-blue-600 uppercase tracking-wide">
                  Question {{ idx + 1 }}
                </span>
                <h3 class="text-sm font-bold text-neutral-900 mt-0.5">
                  {{ q.questionText }}
                </h3>
              </div>

              <!-- Retrieved Authoritative Sources -->
              <div class="space-y-1.5">
                <div class="text-[11px] font-bold text-neutral-500 uppercase tracking-wider">
                  Authoritative Sources Retrieved ({{ q.retrievedUrls.length }})
                </div>
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-2">
                  <a
                    v-for="url in q.retrievedUrls"
                    :key="url.id"
                    :href="url.url"
                    target="_blank"
                    rel="noopener noreferrer"
                    class="flex items-start justify-between gap-2 p-2.5 rounded-lg bg-white border border-neutral-200 hover:border-blue-400 transition-colors group"
                  >
                    <div class="min-w-0 flex-1">
                      <div class="flex items-center gap-1.5 mb-1">
                        <span class="text-[10px] font-bold bg-neutral-100 text-neutral-700 px-1.5 py-0.2 rounded">
                          {{ url.authority }}
                        </span>
                        <span class="text-[10px] text-neutral-500">{{ url.jurisdiction }}</span>
                      </div>
                      <div class="text-xs font-semibold text-neutral-900 truncate group-hover:text-blue-600">
                        {{ url.title }}
                      </div>
                    </div>
                    <ExternalLink class="w-3.5 h-3.5 text-neutral-400 group-hover:text-blue-600 shrink-0 mt-1" />
                  </a>
                </div>
              </div>

              <!-- Answer Markdown View -->
              <div class="space-y-1.5">
                <div class="text-[11px] font-bold text-neutral-500 uppercase tracking-wider">
                  Compliance Analysis & LLM Finding
                </div>
                <div class="p-4 bg-white rounded-xl border border-neutral-200 leading-relaxed whitespace-pre-line text-neutral-800 text-xs sm:text-sm">
                  {{ q.llmAnswer }}
                </div>
              </div>

              <!-- Citations -->
              <div v-if="q.citations && q.citations.length > 0" class="space-y-1.5">
                <div class="text-[11px] font-bold text-neutral-500 uppercase tracking-wider">
                  Verified Statutory Excerpts ({{ q.citations.length }})
                </div>
                <div class="space-y-2">
                  <div
                    v-for="c in q.citations"
                    :key="c.pin"
                    class="p-3 bg-white rounded-xl border border-neutral-200 text-xs space-y-1"
                  >
                    <div class="flex items-center justify-between gap-2">
                      <span class="font-bold text-blue-700 bg-blue-50 px-2 py-0.5 rounded text-[11px]">
                        {{ c.pin }}
                      </span>
                      <span class="text-neutral-500 text-[11px] truncate">{{ c.sourceTitle }}</span>
                    </div>
                    <p class="text-neutral-700 italic border-l-2 border-blue-500 pl-2.5 py-0.5 mt-1">
                      "{{ c.excerpt }}"
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Modal Footer -->
        <div class="px-6 py-4 border-t border-neutral-100 flex items-center justify-between bg-neutral-50/70">
          <span class="text-xs text-neutral-500">
            Exported from Wizpresso Regulatory Monitoring Workspace
          </span>
          <button
            @click="emit('close')"
            class="px-4 py-2 text-xs font-semibold text-neutral-600 hover:text-neutral-900 hover:bg-neutral-100 rounded-xl transition-colors cursor-pointer"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  </Teleport>
</template>
